name = "ImmersedBoundary"
uuid = "3b474169-8a00-48df-8b3c-443b4d82ac46"
version = "0.2.0"
authors = ["pedrosecchi67"]

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
ThreadTools = "dbf13d8f-d36e-4350-8970-f3a99faba1a8"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
DelimitedFiles = "1.9.1"
DocStringExtensions = "0.9.3"
LinearAlgebra = "1.11.0"
NearestNeighbors = "0.4.21"
Serialization = "1.11.0"
ThreadTools = "0.2.1"
WriteVTK = "1.21.1"
